name: Build EXE with Custom DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build EXE with custom DLL
      run: |
        pyinstaller -F generateApiDoc.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe
        path: dist/*.exe
